version: '3'

services:
  # karya-root:
  #   build: .
  #   image: karya-root
  #   container_name: karya-root
  # volumes:
  #   - .:/usr/src/karya
  # command: npx lerna run build

  karya-backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: karya-backend
    depends_on:
      # - karya-root
      - karya-backend-db
      - karya-backend-redis
      # - keycloak
    volumes:
      - .:/usr/src/karya
    ports:
      - 5000:5000
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      - ./backend/.env
    command: node dist/Server.js

  karya-box:
    build:
      context: .
      dockerfile: ./box/Dockerfile
    image: karya-box
    depends_on:
      # - karya-root
      - karya-box-db
    volumes:
      - .:/usr/src/karya
    ports:
      - 8000:8000
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      - ./box/.env
    command: node dist/Server.js

  karya-frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: karya-frontend
    depends_on:
      # - karya-root
      - karya-backend
    volumes:
      - .:/usr/src/karya
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env
    command: serve -s build/ -l 3000

  karya-backend-db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=karya
      - POSTGRES_USER=karya
      - POSTGRES_PASSWORD=karya
    volumes:
      - ./data/psql/backend:/var/lib/postgresql/data

  karya-box-db:
    image: postgres:14-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=box
      - POSTGRES_USER=karya
      - POSTGRES_PASSWORD=karya
    volumes:
      - ./data/psql/box:/var/lib/postgresql/data

  karya-backend-redis:
    image: redis
    ports:
      - 6379:6379

  # keycloak:
  #   image: jboss/keycloak
  #   environment:
  #     - KEYCLOAK_USER=admin
  #     - KEYCLOAK_PASSWORD=password
  #   # volumes:
  #   #   - ./data/keycloak:/opt/jboss/keycloak/standalone/data/
  #   ports:
  #     - 8080:8080
